### ISSUE TITLE
hostname as option

### ISSUE THREAD

**Issue by julianxhokaxhiu** [izatop/dpd#1]
Hi,

I saw your library and looks very cool. Although I saw that you hardcoded the webservice hostname into the source code, and it seems that there is not possibility to change it via options.

What about giving the possibility, and fallback to your hardcoded url? This way you may enable everybody to use this library with DPD Service based on their country of interest to target.

Thank you in advance,
Julian

**Comment by izatop** [comment]
@julianxhokaxhiu thanks for the issue, i'll add an option to define some webservice hostname.
I see it have hardcoded csv file with city list, I can add one more option to define path to it. Agree?

**Comment by julianxhokaxhiu** [comment]
Absolutely! Whatever is required towards targeting should be an option in my opinion :)

Thanks!

**Comment by izatop** [comment]
I have done this issue v.0.3.0-beta and I'll glad to you for any feedback of the version.
To install just type `npm i -S dpd@0.3`

**Comment by julianxhokaxhiu** [comment]
Super awesome! I'm not sure when I will be able to look at the functionality itself, but I'm sure others will find this useful :)

I looked at the commit also and looks good so far. If any bug will come out, a new issue may be opened I guess.

Best regards!

**Comment by izatop** [comment]
Anyway, thank you @julianxhokaxhiu
